name: Run fuzz.py

on:
  # Run the workflow on every push or pull request to the default branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fuzz:
    runs-on: ubuntu-latest  # GitHub-hosted runner (Linux)
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run fuzz.py
        run: |
          python fuzz.py